spring.application.name=product-service
server.port=0
# MongoDB connection :
management.endpoint.health.show-details=always
spring.data.mongodb.uri=mongodb+srv://product_service_user:product_service_password@cluster0.pjaytvd.mongodb.net/products?retryWrites=true&w=majority&appName=Cluster0
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.instance-id=${spring.application.name}:${random.value}
# Resilience4j :
management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-components=true

