spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb+srv://product_service_user:product_service_password@cluster0.pjaytvd.mongodb.net/products?retryWrites=true&w=majority&appName=Cluster0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
server:
  port: 0

  # MongoDB connection :
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      inventory:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        sliding-window-size: 5
        sliding-window-type: count_based
        failure-rate-threshold: 50
        wait-duration-in-open-state: 50s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true